#!/usr/bin/env python
#coding:utf-8
import os
import time
import calendar
import datetime                
def listDir(fileDir):
     for eachFile in os.listdir(fileDir):
        if os.path.isfile(fileDir+"/"+eachFile):   #如果是文件，判断最后修改时间，符合条件进行删除
            ft = os.stat(fileDir+"/"+eachFile);
            ltime = int(ft.st_mtime); #获取文件最后修改时间
            print "不用删除文件"+path+"/"+eachFile+"的最后修改时间为"+str(ltime);
            ntime = int(time.time())-3600*1; #获取现在时间减去1d
            print ntime
            #newname = eachFile + aa +'.zip'
            if ltime<=ntime :         
                print "我要删除文件"+fileDir+"/"+eachFile;
                os.remove(fileDir+"/"+eachFile);   #删除3小时前的文件
        elif os.path.isdir(fileDir+"/"+eachFile) :    #如果是文件夹，继续递归
            listDir(fileDir+"/"+eachFile);
    
if __name__ == '__main__':
    path = "/home/dback";   #规定目录
    listDir(path);
